#pragma once

#define GAME_WIDTH 80
#define GAME_HEIGHT 40
#define PLAYER_OFFSET_X 12
#define BULLET_SPEED 1.5f
#define BULLET_RANGE 80
#define INIT_PLAYER_SPEED 1.5f
#define DASH_SPEED INIT_PLAYER_SPEED * 3.0f
#define DASH_DISTANCE 15
#define DASH_COOLDOWN 450
#define PLAYER_JUMP_STRENGTH 1.2
#define GROUND_HEIGHT 4
#define GRAVITY 0.1f
#define SHOOT_COOLDOWN 300
#define IMMUNE_TIME 1000

#define TICK_DURATION 40
